name: Trigger Repo B workflow via GitHub App

on:
  workflow_dispatch:

jobs:
  trigger:
    runs-on:
      - self-hosted
      - linux
    steps:
      - name: Get token via GitHub App
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: ippanpeople
          repositories: |
            repo2

      - name: Trigger repository_dispatch
        run: |
          curl -X POST https://api.github.com/repos/ippanpeople/repo2/dispatches \
            -H "Authorization: token ${{ steps.generate_token.outputs.token }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d '{"event_type":"on-demand-test","client_payload":{"env": "dev"}}'
